language: scala
jdk:
- openjdk8
scala:
- 2.12.11
- 2.13.1
before_install:
- bash scripts/decrypt_files_if_not_pr.sh
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.cache/coursier -name "*.lock" -type f -delete
cache:
  directories:
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.cache/coursier"
script:
- sbt ++$TRAVIS_SCALA_VERSION test
deploy:
- provider: script
  script: sbt publishRelease
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_SCALA_VERSION = "2.12.11" && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?
